<?php
/**
 * @by SwiftOtter, Inc.
 * @website https://swiftotter.com
 **/

/**
 * @var \SwiftOtter\ProductQuestions\Block\ProductView\Questions $block
 * @var \Magento\Framework\Escaper $escaper
 */

/** @var SwiftOtter\ProductQuestions\ViewModel\ProductView\Questions $viewModel */
$viewModel = $block->getData('view_model');

$questions = $viewModel->getQuestions();
$dateFormat = $block->getData('date_format') ?? \IntlDateFormatter::SHORT;
?>

<div class="product-questions">
    <h3><?= $escaper->escapeHtml($viewModel->getHeading()) ?></h3>

    <?= $block->getChildHtml('post_form') ?>

    <?php foreach ($questions as $question): ?>
        <article class="product-question">
            <header data-role="title">
                <p><?= nl2br($escaper->escapeHtml($question->getContent())) ?></p>
                <aside><?= __(
                        'Asked by user %1 on %2',
                        '<span class="nickname">' . $escaper->escapeHtml($question->getCustomerNickname()) . '</span>',
                        $escaper->escapeHtml($block->formatDate($question->getCreatedAt(), $dateFormat))
                    ) ?></aside>
            </header>
            <div class="question-content" data-role="content">
                <?php $answers = $question->getAnswers() ?? []; ?>
                <?php foreach ($answers as $answer): ?>
                    <section class="product-answer">
                        <p><?= nl2br($escaper->escapeHtml($answer->getContent())) ?></p>
                        <aside><?= __(
                                'Answered by user %1 on %2',
                                '<span class="nickname">' . $escaper->escapeHtml($answer->getCustomerNickname()) . '</span>',
                                $escaper->escapeHtml($block->formatDate($answer->getCreatedAt(), $dateFormat))
                            ) ?></aside>
                    </section>
                <?php endforeach; ?>

                <?= $block->getPostFormHtml((int) $question->getId()) ?>
            </div>
        </article>
    <?php endforeach; ?>
</div>

<script type="text/x-magento-init">
    {
        ".product-questions": {
            "productQuestions": {
                "animationSpeed": 100
            }
        }
    }
</script>
